<a href="https://colab.research.google.com/github/Anvarjondevelop/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
print(pd.__version__)

2.2.2

In [10]:
# Dictionary
mydataset = {
  'cars': ['BMW', 'Volvo', 'Ford', 'Tesla', 'Ferrari', 'Pagani', 'BMW'],
  'counts': [3, 7, 2, 5, 8, 6, 29]
}
print(mydataset, "\n")

df = pd.DataFrame(mydataset)
print(df, "\n")

{'cars': ['BMW', 'Volvo', 'Ford', 'Tesla', 'Ferrari', 'Pagani', 'BMW'], 'counts': [3, 7, 2, 5, 8, 6, 29]}

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       5
4  Ferrari       8
5   Pagani       6
6      BMW      29

In [5]:
df.head(4) # default 5 rows  = > boshidan 5ta qator

    cars  counts
0    BMW       3
1  Volvo       7
2   Ford       2
3  Tesla       5

In [7]:
df.tail(2) # default 5 rows = > oxiridan 5ta qator

     cars  counts
5  Pagani       6
6     BMW       9

In [8]:
# State Property: shape, column, dtypes
a = df.shape
print("=====\n", a)

b = df.columns
print("=====\n", b)

c = df.dtypes # har bir column ning type
print("=====\n", c)

df["cars"] = df["cars"].astype("string")
d = df.dtypes
print("=====\n", d)

=====
 (7, 2)
=====
 Index(['cars', 'counts'], dtype='object')
=====
 cars      object
counts     int64
dtype: object
=====
 cars      string[python]
counts             int64
dtype: object

In [11]:
df.describe()
# df.describe(include="all")

          counts
count   7.000000
mean    8.571429
std     9.253056
min     2.000000
25%     4.000000
50%     6.000000
75%     7.500000
max    29.000000

In [12]:
# iloc (integer location) method

print("=====\n", df.iloc[0])

print("=====\n", df.iloc[1])

print("=====\n", df.iloc[1,0]) # [row location, column location]

print("\n")
df.iloc[1:4]

=====
 cars      BMW
counts      3
Name: 0, dtype: object
=====
 cars      Volvo
counts        7
Name: 1, dtype: object
=====
 Volvo

    cars  counts
1  Volvo       7
2   Ford       2
3  Tesla       5

In [13]:

# loc method
df.loc[1:4, "cars"]

1      Volvo
2       Ford
3      Tesla
4    Ferrari
Name: cars, dtype: object

In [14]:
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       5
4  Ferrari       8
5   Pagani       6
6      BMW      29

In [15]:

df["counts"] >= 3

0     True
1     True
2    False
3     True
4     True
5     True
6     True
Name: counts, dtype: bool

In [16]:
df[df["counts"] >= 3]
# df[df["cars"] == "BMW"]

      cars  counts
0      BMW       3
1    Volvo       7
3    Tesla       5
4  Ferrari       8
5   Pagani       6
6      BMW      29

In [17]:
# mean
a = df.mean(numeric_only=True)
b = df["counts"].mean()

print(a, "\n")
print(b, "\n")

print("======\n")
print(df.min())

print("======\n")
print(df.max())

print("======\n")
print(df.median(numeric_only=True))

print("======\n")
print(df.count())

counts    8.571429
dtype: float64

8.571428571428571

======

cars      BMW
counts      2
dtype: object
======

cars      Volvo
counts       29
dtype: object
======

counts    6.0
dtype: float64
======

cars      7
counts    7
dtype: int64

In [18]:
dataset = {
  'cars': ["BMW", "Volvo", "Ford", None, "Ferrari", "Bugatti", None],
  'counts': [3, 7, 2, None, 8, 14, 17]
}

df_missing = pd.DataFrame(dataset)
print(df_missing, "\n")

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     Ford     2.0
3     None     NaN
4  Ferrari     8.0
5  Bugatti    14.0
6     None    17.0

In [19]:
df_missing.isnull().sum()

cars      2
counts    1
dtype: int64

In [20]:
df_clean = df_missing.dropna()
print(df_clean)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     Ford     2.0
4  Ferrari     8.0
5  Bugatti    14.0

In [21]:
df_missing.dropna(axis=0)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     Ford     2.0
4  Ferrari     8.0
5  Bugatti    14.0

In [23]:
# df_missing.fillna("unknown")
df_missing.fillna({"cars": "unknown", "counts": 0})

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     Ford     2.0
3  unknown     0.0
4  Ferrari     8.0
5  Bugatti    14.0
6  unknown    17.0

In [27]:
# pd.read_excel("Titanic-Dataset.xlsx")
# pd.read_json("Titanic-Dataset.json")

In [28]:
df.to_excel("output.xlsx")
newdf = pd.read_excel("output.xlsx")
newdf.head()

   Unnamed: 0     cars  counts
0           0      BMW       3
1           1    Volvo       7
2           2     Ford       2
3           3    Tesla       5
4           4  Ferrari       8

In [29]:
df.to_excel("test.xlsx", index=False)
newdf = pd.read_excel("output.xlsx")
newdf.head()

   Unnamed: 0     cars  counts
0           0      BMW       3
1           1    Volvo       7
2           2     Ford       2
3           3    Tesla       5
4           4  Ferrari       8

In [30]:
pd.Series(["BMW", "Tesla", "Pagani"])

0       BMW
1     Tesla
2    Pagani
dtype: object